### ISSUE TITLE
api.go error

### ISSUE THREAD

**Issue by FireFox1616** [mitre/sandcat#119]
I downloaded the sandcat.go file on the target computer, but I get this error when trying to execute it:
` panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
_/Users/amanners/MITRE_Projects/caldera/plugins/sandcat/gocat/contact.API.GetInstructions(0xc00005cc30, 0xc000080008)
        /Users/amanners/MITRE_Projects/caldera/plugins/sandcat/gocat/contact/api.go:48 +0x52b
main.runAgent(0x750be0, 0x943650, 0xc00005cc30)
        /Users/amanners/MITRE_Projects/caldera/plugins/sandcat/gocat/sandcat.go:34 +0x448
main.main()
        /Users/amanners/MITRE_Projects/caldera/plugins/sandcat/gocat/sandcat.go:111 +0x658 `

**Comment by khyberspache** [comment]
Most likely your branch isn't up to date. Go into the Sandcat folder and run `git checkout master && git pull` then try deploying the agent again.

**Comment by FireFox1616** [comment]
The git was done the same day when i opened the issue so it was the last existing one. I have seen now that there is an update done something like 3 days ago, i will try again.

**Comment by khyberspache** [comment]
Since there hasn't been any changes, I'll close this for now.  Open a new issue if you are having problems.
