### ISSUE TITLE
Incorrect quotes surrounding the user agent in bash script

### ISSUE THREAD

**Issue by robeving** [mitre/sandcat#13]
In sandcat/templates/54ndc47.sh you are using single quotes around the $user_agent_string.  This is creating the process:

curl --noproxy localhost -sk -X POST -H $user_agent_string -d @- https://localhost:8888/sand/instructions

You need to use different quotes or change your syntax

**Comment by privateducky** [comment]
thanks @robeving; I just updated the agent delivery commands to use a cross-platform agent (written in Golang but compiled for Windows, OSX and Linux). 

we were noticing a number of variations of bash/sh shells that I could for-see being cumbersome to support, so I'm moving us toward a more stable cross-platform (single) agent. this is new, as of a few days ago, so let me know how you like this in comparison.

**Comment by privateducky** [comment]
closing due to the new agent being available.
