### ISSUE TITLE
An error "Interface{} is nill, not string" appears when sandcat is started

### ISSUE THREAD

**Issue by ramus82** [mitre/sandcat#147]
Hello,
I tried to execute a sandcat on my Windows 2016 VM in AWS cloud and I get following error:
`panic: interface conversion: interface {} is nill, not string`

I tried to execute the sandcat under Administrator as well. Same issue

Here you can see the complete output when the sandcat is executed:
```
PS C:\users\public> .\sandcat.exe -server "http://10.X.X.X:8888" -group WinEng
[+] Connectivity not established
[+] beacon: ALIVE
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/api.Instructions(0xc000068f00, 0x1)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/api/api.go:44 +0x4d7
main.askForInstructions(0xc000068f00)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:20 +0x47
main.main()
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:69 +0x2d2
PS C:\users\public>
```

![image](https://user-images.githubusercontent.com/3748215/69234394-50ad8780-0b8f-11ea-86dc-fd25ab0ef852.png)

Connectivity between the Windows host and Caldera instance was checked - it's reachable and port 8888 is accessible.

Thanks for any hints.

**Comment by khyberspache** [comment]
Are you using the release 2.3.2 version?  If not, you need to reclone caldera as that is an old version of the agent.

**Comment by ramus82** [comment]
Hi @khyberspache ,
yes I'm running the 2.3.2 version of Caldera. I expect that the plugins are pulled with version 2.3.2 if this version is explicitly mentioned in git clone (ref. to page of caldera installation).

Thanks

**Comment by khyberspache** [comment]
Did you get that error when trying to run an operation?

**Comment by ramus82** [comment]
The operation on the remote linux host works fine. No issues there. I'm wondering if the issue is not with the Windows 2016 compatibilty and sandcat compiled (maybe) for other platform?

Still testing, let's see.

**Comment by ramus82** [comment]
I tested the sandcat on Windows 2016 and it does not work. It works fine for Win 2012 R2. Linux is also fine. Does anybody has same experience?

**Comment by khyberspache** [comment]
ramus82 I'm going to test out the current version of our agent against 2016 and see if the issue persists.

**Comment by ramus82** [comment]
Today I checked the different AMI in AWS and it works fine. I apologize, the issue was on my side.
