### ISSUE TITLE
Outdated gocat revision linked

### ISSUE THREAD

**Issue by Warfley** [mitre/sandcat#360]
**Describe the bug**
Building errors when including proxy_receiver_http.go occur.

To be a little bit more precise, here is a list of all errors I encountered when compiling gocat:
```bash                                       
# github.com/mitre/gocat/proxy
proxy/proxy_receiver_http.go:52:37: cannot use &HttpReceiver{} (type *HttpReceiver) as type P2pReceiver in assignment:
        *HttpReceiver does not implement P2pReceiver (wrong type for InitializeReceiver method)
                have InitializeReceiver(*string, *contact.Contact, *sync.WaitGroup) error
                want InitializeReceiver(string, contact.Contact, *sync.WaitGroup) error
proxy/proxy_receiver_http.go:308:18: undefined: GetLocalIPv4Addresses
```
```bash
# github.com/mitre/gocat/proxy
proxy/proxy_receiver_http.go:52:37: cannot use &HttpReceiver{} (type *HttpReceiver) as type P2pReceiver in assignment:
        *HttpReceiver does not implement P2pReceiver (wrong type for InitializeReceiver method)
                have InitializeReceiver(*string, *contact.Contact, *sync.WaitGroup) error
                want InitializeReceiver(string, contact.Contact, *sync.WaitGroup) error
```
```bash
# github.com/mitre/gocat/proxy
proxy/proxy_receiver_http.go:52:37: cannot use &HttpReceiver{} (type *HttpReceiver) as type P2pReceiver in assignment:
        *HttpReceiver does not implement P2pReceiver (missing UpdateUpstreamComs method)
```
```bash
# github.com/mitre/gocat/proxy
proxy/proxy_receiver_http.go:52:37: cannot use &HttpReceiver{} (type *HttpReceiver) as type P2pReceiver in assignment:
        *HttpReceiver does not implement P2pReceiver (missing UpdateUpstreamServer method)
```

And when looking into these lines, I found that the changes the buildsystem complains about were pretty recent in the following commit https://github.com/mitre/sandcat/commit/e736a5d8a8a456c852718a90d5004912e0ed3efe

But the linked version of gocat is on commit https://github.com/mitre/gocat/commit/1b4b19cd96627eedea00792d27c8d77a6abb4a7b which is older. So I just checked out master for the gocat repository and it works like a charm.

As I installed caldera with the plugins as suggested in the documentation, via a recursive git clone, master branch of sandcat is checked out, but as it stands the gocat extensions are is not aligned with the state of the code in the gocat repository in the revision referenced. 
 
**To Reproduce**
1. clone sandcat repository (I did so as part of recursively cloning caldera 3.1.0) on branch master
2. copy `gocat-extensions/proxy/proxy_receiver_http.go` to `gocat/proxy`
3. build gocat using `go build`

**Expected behavior**
Successful compilation

**Suggested Solution**
Reference a newer commit of the gocat repository.
OR: Reference an older commit of the sandcat repository in the caldera repository

**System:**
 - OS: Manjaro Linux [Kernel version 5.11.10]
 - Go: version go1.16.2 linux/amd64

**Comment by wbooth** [comment]
thanks I'll take a look and correct

**Comment by wbooth** [comment]
will be fixed going forward, thanks
